### ISSUE TITLE
unable loading {JQUERY} {GOOGLE_ANALYTICS_SCRIPT}  and other javascripts.

### ISSUE THREAD

**Issue by yssource** [greatfire/freegoogle#4]
{JQUERY} {GOOGLE_ANALYTICS_SCRIPT}

**Comment by greatfire-martin** [comment]
Check out the README (https://github.com/greatfire/freegoogle):

The *.htm and *.html files contain a number of variables that need to be replaced with actual values for the mirror to work. We are dynamically replacing these variables when the mirror site is created. The variables are:
- {GOOGLE_IP} - One Google IP address which will be used if the user doesn't have javascript enabled, or if the javascript hasn't yet loaded.
- {GOOGLE_IPS} - List of Google IP addresses. The user will be redirected to the first one that works.
- {GOOGLE_MIRROR_SHORT_URL} - URL used when sharing the mirror site on Sina Weibo.
- {JQUERY} - `<script>` tag for including jquery. Could be for example `<script src="https://lib.sinaapp.com/js/jquery/1.10.2/jquery-1.10.2.min.js"></script>` or `<script src="jquery-1.10.2.min.js"></script>`.
- {PROVIDER_INSTANCE_URLS} - URLs to backend servers that serve Google results using a JSONP callback function (not required).
- {ALT_GOOGLE_MIRRORS} - List of alternative mirrors that the user can be redirected to in order to distribute traffic.
- {GOOGLE_ANALYTICS_SCRIPT} - Code for including Google Analytics (not required).

**Comment by yssource** [comment]
Thanks so much.
The readme tells me it' s able to dynamically replaceing these variables. My understanding is it' s able to this automatically,  isn' t it? 
If i have to replace these shortcodes  manually, I only get knowing the value for {JQUERY }.
I setup this project under apache httpd,  with "localhsot" for testing.

**Comment by ghost** [comment]
Our backend rotates them automatically. But we haven't released the backend code as the code might make GFW easier to block it.
